SchoolManagement/Controllers/MarkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolManagement.ViewModel;
using SchoolManagement.Services;

namespace SchoolManagement.Controllers
{
    public class MarkController : Controller
    {   
        public ActionResult Index()
        {
            try
            {
                MarkServices _objMarkServices = new MarkServices();
                MarkVM _objMarkVM = new MarkVM();
                _objMarkVM.MarkList = new List<MarkVM>();

                _objMarkVM.MarkList = _objMarkServices.GetMarkList();
                return View(_objMarkVM);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        public ActionResult Create(MarkVM _objMarkVM)
        {
            try
            {

                MarkServices _objMarkServices = new MarkServices();
                _objMarkServices.Create(_objMarkVM);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public ActionResult Edit(int Id)
        {
            try
            {
                MarkVM _objMarkVM = new MarkVM();
                _objMarkVM.MarkList = new List<MarkVM>();

                MarkServices _objMarkServices = new MarkServices();

                _objMarkVM = _objMarkServices.GetMarkById(Id);

                return View(_objMarkVM);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        public ActionResult Edit(MarkVM _objMarkVM)
        {
            try
            {

                MarkServices _objMarkServices = new MarkServices();
                _objMarkServices.Update(_objMarkVM);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        public JsonResult Delete(int Id)
        {
            try
            {

                MarkServices _objMarkServices = new MarkServices();
                var result = _objMarkServices.Delete(Id);
                return Json(result);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        public ActionResult GetByStudentId(MarkVM _objMarkVM)
        {
            try
            {
                List<MarkVM> _objMarkVMList = new List<MarkVM>();
                MarkServices _objMarkServices = new MarkServices();
                _objMarkVMList = _objMarkServices.GetByStudentId(_objMarkVM);

                return View("Index", _objMarkVMList);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
    }
}

SchoolManagement/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;
using System.Web.Mvc;
using SchoolManagement.ViewModel;
using SchoolManagement.Services;

namespace SchoolManagement.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult Index()
        {
            try
            {
                StudentServices _objStudentServices = new StudentServices();
                StudentDetailVM _objStudentVM = new StudentDetailVM();
                _objStudentVM.StudentList = new List<StudentDetailVM>();

                _objStudentVM.StudentList = _objStudentServices.GetStudentList();
                return View(_objStudentVM);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        public ActionResult Create(StudentDetailVM _objStudentVM)
        {
            try
            {

                StudentServices _objStudentServices = new StudentServices();
                string ImgName = Path.GetFileName(_objStudentVM.Image.FileName);
                string Imgext = Path.GetExtension(ImgName);
                if(Imgext ==".jpg" || Imgext ==".png")
                {
                    string SavePath = Path.Combine(Server.MapPath("\\Content\\Images\\"), ImgName);
                    _objStudentVM.ImagePath = Path.Combine(("\\Content\\Images\\"), ImgName);
                    _objStudentVM.Image.SaveAs(SavePath);
                }
                _objStudentServices.Create(_objStudentVM);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public ActionResult Edit(int Id)
        {
            try
            {
                StudentDetailVM _objStudentVM = new StudentDetailVM();
                _objStudentVM.StudentList = new List<StudentDetailVM>();

                StudentServices _objStudentServices = new StudentServices();

                _objStudentVM = _objStudentServices.GetStudentById(Id);

                return View(_objStudentVM);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        public ActionResult Edit(StudentDetailVM _objStudentVM)
        {
            try
            {

                StudentServices _objStudentServices = new StudentServices();
                _objStudentServices.Update(_objStudentVM);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        public JsonResult Delete(int Id)
        {
            try
            {

                StudentServices _objStudentServices = new StudentServices();
                var result = _objStudentServices.Delete(Id);
                return Json(result);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
    }
}

SchoolManagement/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolManagement.Services;
using SchoolManagement.ViewModel;

namespace SchoolManagement.Controllers
{
    public class TeacherController : Controller
    {
        // GET: Teacher
        public ActionResult Index()
        {
            try
            {
                TeacherServices _objTeacherServices = new TeacherServices();
                TeacherVM _objTeacherVM = new TeacherVM();
                _objTeacherVM.TeacherList = new List<TeacherVM>();

                _objTeacherVM.TeacherList = _objTeacherServices.GetTeacherList();
                return View(_objTeacherVM);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        public ActionResult Create(TeacherVM _objTeacherVM)
        {
            try
            {

                TeacherServices _objTeacherServices = new TeacherServices();
                _objTeacherServices.Create(_objTeacherVM);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public ActionResult Edit(int Id)
        {
            try
            {
                TeacherVM _objTeacherVM = new TeacherVM();
                _objTeacherVM.TeacherList = new List<TeacherVM>();

                TeacherServices _objTeacherServices = new TeacherServices();

                _objTeacherVM = _objTeacherServices.GetTeacherById(Id);

                return View(_objTeacherVM);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        public ActionResult Edit(TeacherVM _objTeacherVM)
        {
            try
            {

                TeacherServices _objTeacherServices = new TeacherServices();
                _objTeacherServices.Update(_objTeacherVM);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        public JsonResult Delete(int Id)
        {
            try
            {

                TeacherServices _objTeacherServices = new TeacherServices();
                var result = _objTeacherServices.Delete(Id);
                return Json(result);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
    }
}

SchoolManagement/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolManagement.ViewModel;
using SchoolManagement.Services;

namespace SchoolManagement.Controllers
{
    public class UserController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(UserDetailVM _objUserVM)
        {
            try
            {
                UserDetailServices _objUserServices = new UserDetailServices();
                if (_objUserServices.Login(_objUserVM) == true)
                {
                    return RedirectToAction("GetUserList");
                }
                else
                { 
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        public ActionResult GetUserList()
        {
            try
            {
                UserDetailServices _objUserServices = new UserDetailServices();
                UserDetailVM _objUserVM = new UserDetailVM();
                _objUserVM.UserList = new List<UserDetailVM>();

                _objUserVM.UserList = _objUserServices.GetUserList();
                return View(_objUserVM);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        public ActionResult Create(UserDetailVM _objUserVM)
        {
            try
            {

                UserDetailServices _objUserServices = new UserDetailServices();
                _objUserServices.Create(_objUserVM);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public ActionResult Edit(int Id)
        {
            try
            {
                UserDetailVM _objUserVM = new UserDetailVM();
                _objUserVM.UserList = new List<UserDetailVM>();

                UserDetailServices _objUserServices = new UserDetailServices();

                _objUserVM = _objUserServices.GetUserById(Id);

                return View(_objUserVM);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        [HttpPost]
        public ActionResult Edit(UserDetailVM _objUserVM)
        {
            try
            {

                UserDetailServices _objUserServices = new UserDetailServices();
                _objUserServices.Update(_objUserVM);

                return RedirectToAction("GetUserList");
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        public JsonResult Delete(int Id)
        {
            try
            {

                UserDetailServices _objUserServices = new UserDetailServices();
                var result = _objUserServices.Delete(Id);
                return Json(result);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
    }
}

SchoolManagement/Views/User/Create.cshtml
@model SchoolManagement.ViewModel.UserDetailVM
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<script>
    $(document).ready(function () {

    });

    function BacktoIndex() {
        window.location.href = '@Url.Action("GetUserList","User")'
    }
</script>


@using (Html.BeginForm("Create", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row col-md-12">
            <div style="padding:10px;">
                <button type="button" class="btn btn-warning" id="btnBack" onclick="return BacktoIndex();">
                    <i class="glyphicon glyphicon-chevron-left"></i> Back
                </button>
            </div>
            <div>
                @{Html.RenderPartial("_Form");}
            </div>
            <div style="padding:10px;">
                <button type="submit" class="btn btn-success" id="btnSubmit">
                    <i class="glyphicon glyphicon-ok"></i> Submit
                </button>
            </div>
        </div>
    </div>
}

SchoolManagement/Views/User/Edit.cshtml
@model SchoolManagement.ViewModel.UserDetailVM
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<script>
    $(document).ready(function () {
        S
    });

    function BacktoIndex() {
        window.location.href = '@Url.Action("GetUserList","User")'
    }
</script>

@using (Html.BeginForm("Edit", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row col-md-12">
            <div style="padding:10px;">
                <button type="button" class="btn btn-warning" id="btnBack" onclick="return BacktoIndex();">
                    <i class="glyphicon glyphicon-chevron-left"></i> Back
                </button>
            </div>
            <div>
                @{Html.RenderPartial("_Form");}
            </div>
            <div style="padding:10px;">
                <button type="submit" class="btn btn-success" id="btnSubmit">
                    <i class="glyphicon glyphicon-ok"></i> Submit
                </button>
            </div>
        </div>
    </div>
}

SchoolManagement/Views/User/GetUserList.cshtml
@model SchoolManagement.ViewModel.UserDetailVM
@{
    ViewBag.Title = "UserList";
}

<h2>UserList</h2>

<script>
    $(document).ready(function () {
        $('.editBtn').click(function () {
            var Id = parseInt($(this).attr('id'))

            window.location.href = '@Url.Action("Edit", "User")' + '/' + Id;

        });

        $('.deleteBtn').click(function () {
            var Id = parseInt($(this).attr('id'))

            $.ajax({
                url: '@Url.Action("Delete", "User")',
                type: 'POST',
                data: '{Id: "' + Id + '" }',
                contentType: "application/json; charset=utf-8",
                dataType: "html",
                success: function (result) {
                   window.location.href = '@Url.Action("GetUserList", "User")';

                },
                error: function (xhr, ajaxOptions, thrownError) {
                    console.log(thrownError);
                }
            });


        });
    });

</script>

<style>
    .padCont {
        padding: 10px;
    }
</style>


<div class="container">
    <div style="display:flex; justify-content:space-between;">
        <div class="row page-header">
            <div>
                <button class="btn btn-primary padCont" type="button" onclick="window.location.href = '@Url.Action("Index", "Teacher")'">
                    <i class="glyphicon glyphicon-plus"></i> Teachers
                </button>
            </div>
        </div>
        <div class="row page-header">
            <div>
                <button class="btn btn-primary padCont" type="button" onclick="window.location.href = '@Url.Action("Index", "Student")'">
                    <i class="glyphicon glyphicon-plus"></i> Students
                </button>
            </div>
        </div>
        <div class="row page-header">
            <div>
                <button class="btn btn-primary padCont" type="button" onclick="window.location.href = '@Url.Action("Index", "Mark")'">
                    <i class="glyphicon glyphicon-plus"></i> Marks
                </button>
            </div>
        </div>
    </div>
    <div class="form-horizontal">
        <div class="row">
            <div id="Usertable">
                <table class="table table-hover table-condensed" style="background-color:white;">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Gender</th>
                            <th>Designation</th>
                            <th>Address</th>
                            <th>MobileNo</th>
                            <th>Email</th>
                            <th>Password</th>
                            <th>CreatedBy</th>
                            <th>UpdatedBy</th>
                            <th>CreatedDate</th>
                            <th>UpdatedDate</th>
                            <th>Action</th>

                        </tr>
                    </thead>
                    <tbody>
                        @{
                            foreach (var item in Model.UserList)
                            {
                                <tr>
                                    <td>#@item.ID</td>
                                    <td>@item.Name</td>
                                    <td>@item.Gender</td>
                                    <td>@item.Designation</td>
                                    <td>@item.Address</td>
                                    <td>@item.MobileNo</td>
                                    <td>@item.Email</td>
                                    <td>@item.Password</td>
                                    <td>@item.CreatedBy</td>
                                    <td>@item.UpdatedBy</td>
                                    <td>@item.CreatedDate.ToString("dd/MM/yyyy")</td>
                                    <td>@item.UpdatedDate.ToString("dd/MM/yyyy")</td>

                                    <td>
                                        <span class="btn btn-info padCont editBtn" id="@item.ID"><i class="glyphicon glyphicon-edit"></i> Edit</span>
                                        <span class="btn btn-danger padCont deleteBtn" id="@item.ID"><i class="glyphicon glyphicon-trash"></i> Delete</span>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

SchoolManagement/Views/User/Index.cshtml
@model SchoolManagement.ViewModel.UserDetailVM
@{
    ViewBag.Title = "Index";
}

<h2>Login</h2>
<style>
    body{
        align-items: center;
       margin-left:30%;
        color:white;
    }
   
     
    a{
        color: white;
        margin-left:15px;
    }
</style>

@using (Html.BeginForm("Index", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
<div class="body">

    <div class="col-md-12 form-group row">
        <div class="col-md-4">
            <div class="col-sm-4 col-form-label">
                @Html.LabelFor(model => model.Email, "Email")
            </div>
            <div class="col-sm-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control-plaintext", @id = "txtEmail" } })
            </div>
        </div>
    </div>
    <div class="col-md-12 form-group row">
        <div class="col-md-4">
            <div class="col-sm-4 col-form-label">
                @Html.LabelFor(model => model.Password, "Password")
            </div>
            <div class="col-sm-10">
                @Html.PasswordFor(model => model.Password, new { type="password", htmlAttributes = new { @class = "form-control-plaintext", @id = "txtPassword" } })
            </div>
        </div>
    </div>

        <div style="padding:10px;">
            <button class="btn btn-primary padCont" type="submit" style="margin-left:40px;">
                Submit
            </button>
        </div>
        <div>
            <a onclick="window.location.href = '@Url.Action("Create", "User")'" style="cursor:pointer; margin-top:20px;">New User? Register Here</a>
        </div>
    </div>
}

SchoolManagement/Views/User/_Form.cshtml
@model SchoolManagement.ViewModel.UserDetailVM

<style>
    .row {
        padding: 10px
    }
</style>

<div class="form-horizontal">
    <div class="col-md-12">
        @Html.HiddenFor(model => model.ID)
        <div class="row">
            <div class="col-md-6">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Name)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control reset", @id = "txtName" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Gender)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control reset", @id = "txtGender" } })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Designation)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control reset", @id = "txtDesignation" } })
                    @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Address)
                </div>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control reset", @id = "txtAddress" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.MobileNo)
                </div>
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.MobileNo, new { @class = "form-control reset", @id = "txtMobileNO" })
                    @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Email)
                </div>
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control reset", @id = "txtEmail" })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Password)
                </div>
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.Password, new { @class = "form-control reset", @id = "txtPassword" })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-6">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.CreatedBy)
                </div>
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.CreatedBy, new { @class = "form-control reset", @id = "txtCreatedBy" })
                    @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.UpdatedBy)
                </div>
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.UpdatedBy, new { @class = "form-control reset", @id = "txtUpdatedBy" })
                    @Html.ValidationMessageFor(model => model.UpdatedBy, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
</div>